// <auto-generated />
using System;
using FrontEnd.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FrontEnd.Persistence.Migrations
{
    [DbContext(typeof(FrontEndDbContext))]
    partial class FrontEndDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Domain.Models.FarmLocationModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EntityModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TenantModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantModelId");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("Domain.Models.LandPlotModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Area")
                        .HasColumnType("TEXT");

                    b.Property<long>("AreaUnit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EntityModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<long>("FarmLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FarmLocationModelId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LandPlotModelId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentPlotId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Usage")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FarmLocationModelId");

                    b.HasIndex("LandPlotModelId");

                    b.ToTable("LandPlots");
                });

            modelBuilder.Entity("Domain.Models.TenantModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EntityModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TenantUserAdminId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Domain.Models.FarmLocationModel", b =>
                {
                    b.HasOne("Domain.Models.TenantModel", null)
                        .WithMany("Farms")
                        .HasForeignKey("TenantModelId");
                });

            modelBuilder.Entity("Domain.Models.LandPlotModel", b =>
                {
                    b.HasOne("Domain.Models.FarmLocationModel", null)
                        .WithMany("Plots")
                        .HasForeignKey("FarmLocationModelId");

                    b.HasOne("Domain.Models.LandPlotModel", null)
                        .WithMany("Subplots")
                        .HasForeignKey("LandPlotModelId");
                });

            modelBuilder.Entity("Domain.Models.FarmLocationModel", b =>
                {
                    b.Navigation("Plots");
                });

            modelBuilder.Entity("Domain.Models.LandPlotModel", b =>
                {
                    b.Navigation("Subplots");
                });

            modelBuilder.Entity("Domain.Models.TenantModel", b =>
                {
                    b.Navigation("Farms");
                });
#pragma warning restore 612, 618
        }
    }
}
